uart: initial commit
freechipsproject/ip-contributions pull request #6
Opened 2019-10-09 09:36 UTC by schoeberl

Have a serial port in the library.

2019-10-11 21:49 UTC, schoeberl commented
What is the protocol to contribute to this repo? Who is merging?

Cheers,
Martin

> On 9 Oct, 2019, at 5:36, Martin Schoeberl <notifications@github.com> wrote:
> 
> Have a serial port in the library.
> 
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/freechipsproject/ip-contributions/pull/6 <https://github.com/freechipsproject/ip-contributions/pull/6>
> Commit Summary
> 
> uart: initial commit
> File Changes
> 
> M README.md <https://github.com/freechipsproject/ip-contributions/pull/6/files#diff-0> (2)
> A src/main/scala/chisel/lib/uart/README.md <https://github.com/freechipsproject/ip-contributions/pull/6/files#diff-1> (11)
> A src/main/scala/chisel/lib/uart/Uart.scala <https://github.com/freechipsproject/ip-contributions/pull/6/files#diff-2> (218)
> A src/test/scala/chisel/lib/uart/UartTester.scala <https://github.com/freechipsproject/ip-contributions/pull/6/files#diff-3> (93)
> Patch Links:
> 
> https://github.com/freechipsproject/ip-contributions/pull/6.patch <https://github.com/freechipsproject/ip-contributions/pull/6.patch>
> https://github.com/freechipsproject/ip-contributions/pull/6.diff <https://github.com/freechipsproject/ip-contributions/pull/6.diff>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub <https://github.com/freechipsproject/ip-contributions/pull/6?email_source=notifications&email_token=AAE63GCIWU2KHE2TT2U3IG3QNWQZVA5CNFSM4I64YBS2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HQSRABA>, or mute the thread <https://github.com/notifications/unsubscribe-auth/AAE63GC55A75SUQUNYA5ERTQNWQZVANCNFSM4I64YBSQ>.
>

2019-10-11 21:58 UTC, seldridge reviewed
Two comments.

2019-10-11 21:58 UTC, seldridge commented on src/main/scala/chisel/lib/uart/Uart.scala
> +}
Two comments:
1. Is there a reason why this is `Bits(8.W)` instead of `UInt(8.W)`? Currently, [`object Bits extends UIntFactory`](https://github.com/freechipsproject/chisel3/blob/fafd984a923591841917cd4c3a1f4c823dc485b4/chiselFrontend/src/main/scala/chisel3/package.scala#L138). So, this is equivalent, but I think use of `Bits` is discouraged?
2. It seems logical to use `Decoupled` here instead of a one-off ready/valid interface.

2019-10-13 01:18 UTC, schoeberl commented
> On 11 Oct, 2019, at 17:58, Schuyler Eldridge <notifications@github.com> wrote:
> 
> @seldridge commented on this pull request.
> 
> Two comments.
> 
> In src/main/scala/chisel/lib/uart/Uart.scala <https://github.com/freechipsproject/ip-contributions/pull/6#discussion_r333129226>:
> 
> > +class Channel extends Bundle {
> +  val data = Input(Bits(8.W))
> +  val ready = Output(Bool())
> +  val valid = Input(Bool())
> +}
> Two comments:
> 
> Is there a reason why this is Bits(8.W) instead of UInt(8.W)? Currently, object Bits extends UIntFactory <https://github.com/freechipsproject/chisel3/blob/fafd984a923591841917cd4c3a1f4c823dc485b4/chiselFrontend/src/main/scala/chisel3/package.scala#L138>. So, this is equivalent, but I think use of Bits is discouraged?
> It seems logical to use Decoupled here instead of a one-off ready/valid interface.

You are right with Bits. They are kind of dead now… Although this would be the very perfect place where it should be Bits and not UInt. An ASCII character is not an unsigned integer.

Yes, it could (should) be Decoupled. Was just in the first place to be more self contained.

Cheers,
Martin

2019-10-13 23:55 UTC, chick requested changes
Thanks for the contribution.
I think this looks like a good offering but I think the tests need to
have some expect operations that test whether things are actually working.
Currently they seem to be more just use examples.

2019-10-15 16:06 UTC, schoeberl commented
You are right. However, hardware that connects to the outer world is hard to test in simulation.
It has been tested in an FPGA with a UART connected to a laptop.

I will try to come up with a better test.

Cheers,
Martin

> On 13 Oct, 2019, at 19:55, Chick Markley <notifications@github.com> wrote:
> 
> @chick requested changes on this pull request.
> 
> Thanks for the contribution.
> I think this looks like a good offering but I think the tests need to
> have some expect operations that test whether things are actually working.
> Currently they seem to be more just use examples.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/freechipsproject/ip-contributions/pull/6?email_source=notifications&email_token=AAE63GFCQL4DZMHALOAL4ITQOOYOPA5CNFSM4I64YBS2YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCHZA2KA#pullrequestreview-301075752>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AAE63GFQKLTJWFEZOEZA7MDQOOYOPANCNFSM4I64YBSQ>.
>

2019-10-15 20:13 UTC, schoeberl commented
change done, ready for (re)review

2019-10-15 20:18 UTC, chick reviewed
Tests look good to me.
One question before approving.

I notice that there are still several declarations of Bits instead of UInt. It appeared from your conversation with @seldridge that you would change these to UInt. If you make those changes I will just approve. Otherwise, do you want to make a case still for keeping Bits. I don't have strong feelings but I lean towards @seldridge's position because Bits() returns UInt() and that may be confusing

2019-10-15 20:22 UTC, seldridge commented
Or: `Bits(1.W)` is better semantically expressed as `Bool()`.

2019-10-15 20:28 UTC, schoeberl commented
I agree that a ready or valid signal may be a Bool, as it has a Boolean meaning. However, a data line is not true or false. So for me this is not a Bool.

I can change to UInt (for now). Maybe we can discuss the future of Bits in Chisel one more time ;-)

Cheers,
Martin

> On 15 Oct 2019, at 16:22, Schuyler Eldridge <notifications@github.com> wrote:
> 
> Or: Bits(1.W) is better semantically expressed as Bool().
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2019-10-15 20:34 UTC, chick approved these changes
Looks great, thanks for the contribution

2019-10-15 20:39 UTC, schoeberl commented
Thanks! @chick are you doing the merge? I don't have write access ;-)

2019-10-15 20:50 UTC, merged

2019-10-15 20:50 UTC, chick commented
@schoeberl Done! Thanks again