Add different FIFO implementations
freechipsproject/ip-contributions pull request #9
Opened 2019-10-16 20:21 UTC by schoeberl

2019-10-18 18:06 UTC, chick requested changes

2019-10-18 18:06 UTC, chick commented on src/main/scala/chisel/lib/fifo/BubbleFifo.scala
> +  private class Buffer[T <: Data](gen: T) extends Module {
I think that you do not need `[T <: Data]` here, because it probably is the same `T` as in the outer class.
In fact I am not sure that you need the `gen` parameter at all, I think you can just call the `gen` from the outer class in your private class directly

2019-10-18 18:06 UTC, chick commented on src/main/scala/chisel/lib/fifo/README.md
> +Different implementations of FIFO queues. Small queus can be register based
Nit: typo in  word "queus"

2019-10-18 18:06 UTC, chick commented on src/main/scala/chisel/lib/fifo/BubbleFifo.scala
> +/*
Style guide calls for top of file to be
>// See README.md for license details.
>
We should probably enforce this or drop this style guide item. Any thoughts?

2019-10-18 18:06 UTC, chick commented on src/main/scala/chisel/lib/fifo/BubbleFifo.scala
> +  private val buffers = Array.fill(depth) { Module(new Buffer(gen)) }
I think many of these Modules may have problems in the degenerate case where the depth is zero. You might consider adding an assert or require to protect against this, or rewrite the loop to handle this.
The following more complex formulation handles the zero and other cases I think
```scala
  private val buffers = Array.fill(depth) { Module(new Buffer) }

  (Seq(io.enq) ++  buffers.map(_.io.deq)).zip(buffers.map(_.io.enq) :+ io.deq).foreach { case (prev, next) =>
    next <> prev
  }
```
It seems to me there is a constant tension in libraries like this between writing in a very plain style vs demonstrating the power of comprehensions. I'll leave that decision here for you.

2019-10-19 01:36 UTC, schoeberl commented
@chick, thank you for your feedback. Very much appreciated!

It should be fixed now (expect the one liner, see below)

> On 18 Oct, 2019, at 14:06, Chick Markley <notifications@github.com> wrote:
> Style guide calls for top of file to be
> 
> // See README.md for license details.
> 
> We should probably enforce this or drop this style guide item. Any thoughts?
> 
> 

I don't see any style guide (in this repo) for the single line reference to README. Actually I am easy on which license to use as long as it is a liberal one. However, when we use the proposed unlicense, the file might be copied without copying the README. Therefore, I would propose to keep a minimal pointer to the license and also the author in each file. I would like to sign the SW I wrote with my name on a per source file base.

BTW, shouldn't we have a LICENSE.md file in the GitHub instead of the license in README.md?

>   private val buffers = Array.fill(depth) { Module(new Buffer) }
> 
>   (Seq(io.enq) ++  buffers.map(_.io.deq)).zip(buffers.map(_.io.enq) :+ io.deq).foreach { case (prev, next) =>
>     next <> prev
>   }
> It seems to me there is a constant tension in libraries like this between writing in a very plain style vs demonstrating the power of comprehensions. I'll leave that decision here for you.
> 
> 
Thanks. I would like to keep my code readable also for developers with no/less background in functional programming. I might change my mind in the future. Students will tell me ;-)

Cheers,
Martin

2019-10-21 20:13 UTC, chick approved these changes
Looks good to me, thanks for the contribution

2019-10-21 20:13 UTC, merged